repos:
  - repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
    - id: cpplint
      name: cpplint
      description: Static code analysis of C/C++ files
      language: python
      files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
      entry: cpplint
